### ISSUE TITLE
Handle out-of-range values better

### ISSUE THREAD

**Issue by dala318** [dala318/python_poollab#21]
Got an OR measurement on Cyanic Acid and was read by integration as 100 000 000 000 PPM.
![image](https://github.com/dala318/python_poollab/assets/20300390/3a54c7db-bc4c-44fe-a89d-7b4e0e5d9528)

**Comment by dala318** [comment]
Yet no good way to handle this systematically. 
Would need to define some good MAX/MIN value for each sensor type.
Root cause is that this is actually the value that is reported from API

**Comment by FirelightLokeren** [comment]
Hi dala318.

I sugest to use the valeus from the usermanual.
PH (Phenol Red) : UR - 6.5 - 8.4 -OR
Chlorine (DPD1 and DPD 3): 0 - 8.00 - OR
CYA: 0 - 160 -OR
[https://poollab.org/static/manuals/poollab_manual_gb-fr-e-d-i.pdf](url)

**Comment by ScratMan** [comment]
I faced the same issue yesterday measuring free chlorine as out of range, it appeared as 1 million of mg/l, breaking curve's scaling.
